### ISSUE TITLE
Create Sphinx documentation in gh-pages branch

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab-documentation#48] opened 2019-10-22 09:34 UTC
Build a documentation website using CNAME docs.pslab.io in gh-pages branch.
* Use travis CI to build the site automatically on every merged PR

Pointers:
* https://gist.github.com/domenic/ec8b0fc8ab45f39403dd
* https://github.com/Syntaf/travis-sphinx
* https://medium.com/akeneo-labs/documentation-on-steroids-with-sphinx-github-travis-ci-and-platform-sh-89218513d136

**Comment by priyanshunayan** [comment] 2019-11-06 16:19
@mariobehling can I work on this issue?

**Comment by mariobehling** [comment] 2019-11-07 02:58
No need to ask for issues that are open for some time and where is no activity. Just go ahead and make a PR when you are ready.

**Comment by kumuditha-udayanga** [comment] 2020-01-10 19:07
I'm working on it  🙂

**Comment by kumuditha-udayanga** [comment] 2020-01-15 13:50
@mariobehling sir the issue is been fixed please review :)

**Comment by mariobehling** [comment] 2020-01-21 07:41
The next step is to make the Travis build work and to deploy the site in the gh-pages branch.
[![Build Status](https://www.travis-ci.org/fossasia/pslab-documentation.svg?branch=master)](https://www.travis-ci.org/fossasia/pslab-documentation)

**Comment by orangecms** [comment] 2020-08-13 20:20
Deployment is now in place, so closing this.

**Closed by orangecms** 2020-08-13 20:20 UTC
