### ISSUE TITLE
PSLab Experiment: Finding directions using phone.

### ISSUE THREAD

**Issue by Devansh3712** [fossasia/pslab-documentation#62] opened 2020-01-05 09:31 UTC
**Describe the issue**

I am conducting an experiment to find directions using PSLab android app.

**Would you like to work on the issue?**

Yes, I would love to work on the issue.

>>>The Experiment

AIM: To find directions using PSLab in an android phone.

MATERIALS REQUIRED: Android Phone with PSLab installed and having compass sensor.

PROCEDURE: 
1. First of all install PSLab from Playstore in your android phone and open the application.
2. After opening the app, search for Compass instrument in the app and open it.
3. On opening the instrument, you'll see a dial with 4 vertices, namely North (N), South (S), East (E), West (W).
4. Rotate your device 360 degrees to check whether it is working or not and calibrate it. The instrument also has sub vertices for South East (SE), North East (NE), South West (SW) and North West (NW).
5. Now you can check the directions using this instrument by only your android phone!

OBSERVATIONS:
1. The PSLab application shows the right direction on being rotated.
2. The application is accurate in showing directions.
3. Really easy to use and a perfect interface for android.

RESULT:
Therefore, we can find directions from android phone using the PSLab's Compass intrument.

![Screenshot_20200105-145718](https://user-images.githubusercontent.com/58616444/71777871-3a874980-2fcc-11ea-8cf9-0a9b9b66a671.jpg)
![Screenshot_20200105-145728](https://user-images.githubusercontent.com/58616444/71777872-3a874980-2fcc-11ea-948e-19d765742360.jpg)
![2020-01-05 14_58_09 519_graph](https://user-images.githubusercontent.com/58616444/71777870-39eeb300-2fcc-11ea-929d-e7b8c4027175.jpg)

**Comment by NishithP2004** [comment] 2020-01-05 15:03
There is tutorial already added for this issue and therefore this issue may be closed.

**Comment by NishithP2004** [comment] 2020-01-05 15:04
Duplicate of #60

**Comment by orangecms** [comment] 2020-08-16 18:11
Agreed to this being a duplicate, closing thusly.

**Closed by orangecms** 2020-08-16 18:11 UTC
